package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	registryPath := filepath.Join(root, "registry_types.go")
	content, err := os.ReadFile(registryPath)
	if err != nil {
		panic(err)
	}

	re := regexp.MustCompile(`"([A-Za-z0-9_]+)"`)
	matches := re.FindAllStringSubmatch(string(content), -1)
	if len(matches) == 0 {
		panic("no type names found in registry_types.go")
	}

	seen := map[string]bool{}
	names := make([]string, 0, len(matches))
	for _, match := range matches {
		name := match[1]
		if seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}

	var out strings.Builder
	out.WriteString("// Code generated by tools/gen_registry; DO NOT EDIT.\n\n")
	out.WriteString("package types\n\n")
	out.WriteString("var baseCodecFactories = map[string]CodecFactory{\n")
	for _, name := range names {
		out.WriteString(fmt.Sprintf("\t%q: func() Decoder { return &%s{} },\n", strings.ToLower(name), name))
	}
	out.WriteString("}\n")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		panic(err)
	}

	outPath := filepath.Join(root, "registry_gen.go")
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		panic(err)
	}
}
